package ch.so.agi.csv2parquet.meta;

public enum DataType {
    BOOLEAN, TEXT, MTEXT, JSON_TEXT, INTEGER, DOUBLE, DATE, DATETIME, ENUMERATION, POLYGON, LINESTRING, POINT, MULTIPOLYGON, MULTILINESTRING, MULTIPOINT, STRUCTURE, UNDEFINED  
}
