[ch.so.agi.amtliche_vermessung.statistik]
title="Ich bin ein Titel"
description="Ich bin eine Beschreibung"

[ch.so.agi.amtliche_vermessung.statistik.umsatz]
title="Ressourcen-Title... Umsatz"
description="Ressourcen Beschreibung"
firstLineIsHeader=true
models="SO_AGI_Amtliche_Vermessung_Statistik_Umsatz_20230625"
